export const etiquetas = {
  lblInicioSesion: 'Inicio de sesión',
  lblCredenciales: 'Ingrese sus credenciales',
  lblOlvidoPassword: '¿Olvidó su contraseña?',
  lblUsuario: 'Usuario',
  lblPassword: 'Contraseña',
  btnIngresar: 'Ingresar',
  btnRegistrarse: 'Registrarse',
  btnIniciarSesion: 'Iniciar sesión',
  btnCancelar: 'Cancelar',
  btnCreateTask: 'Crear tarea',
  btnLogout: 'Cerrar sesión',
  btnEliminar: 'Eliminar',
  btnMover: 'Mover',
  btnConfirmDelete: 'Si, eliminar',
  ErrorLogin: 'Los campos usuario y contraseña son obligatorios',
  NameRequired: 'El campo nombre es obligatorio',
  PatronymicRequired: 'El campo apellido es obligatorio',
  EmailRequired: 'El campo email es obligatorio',
  PasswordRequired: 'El campo contraseña es obligatorio',
  UserNameRequired: 'El campo usuario es obligatorio',
  lblRegistroUsuarios: 'Registro de usuarios',
  lblTitleRegisterUsers: 'Por favor ingrese los datos del formulario para crear su cuenta.',
  lblEmail: 'Email',
  lblApellido: 'Apellido',
  lblNombre: 'Nombre',
  lblTaskRequired: 'Los campos nombre y descripción de la tarea son obligatorios',
  lblNewTasks: 'Nuevas tareas',
  lblTaskProgreso: 'En progreso',
  lblTaskTerminadas: 'Terminadas',
  lblRegisterTasks: 'Registro de tareas',
  lblNameTask: 'Nombre de la tarea',
  lblDescriptionTask: 'Descripción de la tarea',
  lblActionsTasks: 'Acciones para tareas',
  lblMoveTask: 'Mover la tarea a:',
  lblDeleteTasks: 'Eliminar tareas',
  lblQuestionDeleteTask: '¿Esta seguro de eliminar la tarea seleccionada?',
}